manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: robomaster-dlmu
      url-base: https://github.com/RoboMaster-DLMU-CONE

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import:
        name-allowlist:
          - cmsis
          - cmsis_6
          - hal_stm32
    - name: onemotor
      remote: robomaster-dlmu
      repo-path: OneMotor
      revision: main
      path: modules/lib/onemotor
    - name: rpl
      remote: robomaster-dlmu
      repo-path: rpl
      revision: main
      path: modules/lib/rpl