set(OF_TOTAL_HEAP_SIZE 0 CACHE INTERNAL "累计的堆内存需求")
function(one_framework_init)
    one_framework_finalize_heap_size()
endfunction()
include(${CMAKE_CURRENT_LIST_DIR}/OFUnit.cmake)
message(STATUS "-- One Framework build system activated --")